version: '3'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    user: node
    entrypoint:
      - '/code/entrypoint.sh'
    environment:
      - API_URI=http://core:8000/graphql/
    volumes:
      - ./:/code
    ports:
      - "3000:3000"

